#@ load("@ytt:data", "data")

apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: my-tanzu-rabbit
spec:
  replicas: #@ data.values.rabbitmq.replicas
  imagePullSecrets:
  - name: tanzu-rabbitmq-registry-creds
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers: []
            #@ if data.values.openshift == 1:
            securityContext: {}
            #@ end

