#@ load("@ytt:data", "data")

apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: tanzu-rabbitmq
spec:
  serviceAccountName: #@ data.values.rabbitmq.serviceaccount
  packageRef:
    refName: rabbitmq.tanzu.vmware.com
    versionSelection:
      constraints: #@ data.values.rabbitmq.version
