apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: production-ready-tanzu-rabbitmq
spec:
  maxUnavailable: #@ data.values.rabbitmq.max_unavailable
  selector:
    matchLabels:
      app.kubernetes.io/name: tanzu-rabbitmq