apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: production-ready-tanzu-rabbitmq
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tanzu-rabbitmq